#! /bin/sh
#rm /Applications/Plone2/Sites/devel/Products/PloneRadio/*.py /Applications/Plone2/Sites/devel/Products/PloneRadio/Extensions/*
/Developer/Zope/ArchGenXML/ArchGenXML.py --author="Wolfgang Reutz" --e-mail="wolfgang.reutz@fhv.at" --copyright="Fachhochschule Vorarlberg" -o ../ PloneRadio.zuml
