#! /bin/sh
#rm /Applications/Plone2/Sites/devel/Products/PloneRadio/*.py /Applications/Plone2/Sites/devel/Products/PloneRadio/Extensions/*
archgenxml --i18n-support --author="Wolfgang Reutz" --e-mail="wolfgang.reutz@fh-vorarlberg.ac.at" --copyright="Fachhochschule Vorarlberg" -o ../ PloneRadio.zuml
